version: "3.9"

services:
  app:
    build: .
    container_name: adoptme_app
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: ["node", "app.js"]

  mongo:
    image: mongo
    container_name: adoptme_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
