version: "3.8"

services:
  mongo:
    image: mongo
    container_name: adoptme_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: adoptme_app
    ports:
      - "8081:8081"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
    environment:
      - PORT=8081
      - MONGO_URI=mongodb://mongo:27017/adoptme
    command: node src/app.js

volumes:
  mongo-data:
